<def f='llvm/llvm/include/llvm/Support/Error.h' l='939' ll='949' type='Expected&lt;T&gt; llvm::handleExpected(Expected&lt;T&gt; ValOrErr, RecoveryFtor &amp;&amp; RecoveryPath, HandlerTs &amp;&amp;... Handlers)'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='637' u='c' c='_ZN12_GLOBAL__N_132Error_HandleExpectedSuccess_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='658' u='c' c='_ZN12_GLOBAL__N_139Error_HandleExpectedUnhandledError_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='676' u='c' c='_ZN12_GLOBAL__N_137Error_HandleExpectedHandledError_Test8TestBodyEv'/>
