<def f='llvm/llvm/include/llvm/Support/Error.h' l='391' ll='415' type='static llvm::Error llvm::ErrorList::join(llvm::Error E1, llvm::Error E2)'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='424' u='c' c='_ZN4llvm10joinErrorsENS_5ErrorES0_'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='891' u='c' c='_ZN4llvm12handleErrorsENS_5ErrorEDpOT_'/>
