<use f='llvm/llvm/include/llvm/ADT/fallible_iterator.h' l='130' u='c' c='_ZN4llvm17fallible_iteratorppEv'/>
<use f='llvm/llvm/include/llvm/ADT/fallible_iterator.h' l='146' u='c' c='_ZN4llvm17fallible_iteratormmEv'/>
<def f='llvm/llvm/include/llvm/ADT/fallible_iterator.h' l='206' ll='210' type='void llvm::fallible_iterator::handleError(llvm::Error Err)'/>
