<def f='llvm/llvm/utils/unittest/googletest/src/gtest-internal-inl.h' l='803' type='bool testing::internal::UnitTestImpl::catch_exceptions() const'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest.cc' l='2435' u='c' c='_ZN7testing8internal35HandleExceptionsInMethodIfSupportedEPT_MS1_FT0_vEPKc'/>
<doc f='llvm/llvm/utils/unittest/googletest/src/gtest-internal-inl.h' l='801'>// Returns the value of GTEST_FLAG(catch_exceptions) at the moment
  // UnitTest::Run() starts.</doc>
