<def f='llvm/clang/include/clang/Sema/Scope.h' l='332' ll='334' type='bool clang::Scope::hasUnrecoverableErrorOccurred() const'/>
<use f='llvm/clang/lib/Sema/SemaDecl.cpp' l='1841' u='c' c='_ZN5clang4Sema13ActOnPopScopeENS_14SourceLocationEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaDeclObjC.cpp' l='5054' u='c' c='_ZN5clang4Sema35DiagnoseUnusedBackingIvarInAccessorEPNS_5ScopeEPKNS_22ObjCImplementationDeclE'/>
